version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: docker/server/dev.Dockerfile
    ports:
      - 8000:8000
    environment:
      - IN_DOCKER=True
    volumes:
      - static_volume:/usr/src/app/backend/staticfiles
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  static_volume:
  postgres_data: