version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: docker/server/dev.Dockerfile
    ports:
      - 8000:8000
    environment:
      - IN_DOCKER=True
    volumes:
      - static_volume:/usr/src/app/backend/staticfiles

volumes:
  static_volume:
