# Generated by Django 3.2 on 2021-04-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videothumbnail',
            options={'verbose_name': 'Video Thumbnail', 'verbose_name_plural': 'Video Thumbnails'},
        ),
    ]
